install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-1.6.0-i686-pc-windows-gnu.exe'
  - rust-1.6.0-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --verbose

artifacts:
  - path: ./target/